-- 코드를 입력하세요
SELECT A.PRODUCT_CODE, SUM(A.PRICE * B.SALES_AMOUNT) as SALES
FROM PRODUCT A
JOIN OFFLINE_SALE B on A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY SALES desc, A.PRODUCT_CODE